// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// drill_parse
SEXP drill_parse(std::string meta_s, std::string data_s);
RcppExport SEXP _sergeant_drill_parse(SEXP meta_sSEXP, SEXP data_sSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type meta_s(meta_sSEXP);
    Rcpp::traits::input_parameter< std::string >::type data_s(data_sSEXP);
    rcpp_result_gen = Rcpp::wrap(drill_parse(meta_s, data_s));
    return rcpp_result_gen;
END_RCPP
}
// drill_field_init
SEXP drill_field_init(std::string json, std::string value);
RcppExport SEXP _sergeant_drill_field_init(SEXP jsonSEXP, SEXP valueSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type json(jsonSEXP);
    Rcpp::traits::input_parameter< std::string >::type value(valueSEXP);
    rcpp_result_gen = Rcpp::wrap(drill_field_init(json, value));
    return rcpp_result_gen;
END_RCPP
}
// drill_parse_files
SEXP drill_parse_files(std::string schema_path, std::vector<std::string> file_paths, int n, bool quiet);
RcppExport SEXP _sergeant_drill_parse_files(SEXP schema_pathSEXP, SEXP file_pathsSEXP, SEXP nSEXP, SEXP quietSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type schema_path(schema_pathSEXP);
    Rcpp::traits::input_parameter< std::vector<std::string> >::type file_paths(file_pathsSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< bool >::type quiet(quietSEXP);
    rcpp_result_gen = Rcpp::wrap(drill_parse_files(schema_path, file_paths, n, quiet));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_sergeant_drill_parse", (DL_FUNC) &_sergeant_drill_parse, 2},
    {"_sergeant_drill_field_init", (DL_FUNC) &_sergeant_drill_field_init, 2},
    {"_sergeant_drill_parse_files", (DL_FUNC) &_sergeant_drill_parse_files, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_sergeant(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
