# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

drill_parse <- function(meta_s, data_s) {
    .Call(`_sergeant_drill_parse`, meta_s, data_s)
}

drill_field_init <- function(json, value = "") {
    .Call(`_sergeant_drill_field_init`, json, value)
}

drill_parse_files <- function(schema_path, file_paths, n, quiet) {
    .Call(`_sergeant_drill_parse_files`, schema_path, file_paths, n, quiet)
}

